### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by SomebodySmart** [codeguy/modern-php#2]
I use register.php and the server does not like line 17

Parse error: syntax error, unexpected '[' in /home/obits/public_html/register.php on line 17

That's the line that says, [' cost' => 12] 
Hint: I have no idea what I'm doing. What am I doing wrong?

**Comment by codeguy** [comment]
You need to use PHP 5.4 or newer to use the newer array syntax.

**Comment by codeguy** [comment]
Closing this issue. But feel free to continue conversation. I'm here if you have any questions.

**Comment by codeguy** [comment]
Also, you can change that particular code example to this to make it work in earlier versions:

```
array('cost' => 12)
```
